In [22]:
from tensorflow.keras.preprocessing.text import one_hot

In [23]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [24]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [25]:
## Define the vocabulary size
voc_size=10000

In [26]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [27]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9128, 5596, 8740, 2201],
 [9128, 5596, 8740, 5864],
 [9128, 8216, 8740, 7432],
 [4452, 7897, 594, 2600, 4104],
 [4452, 7897, 594, 2600, 50],
 [3889, 9128, 1393, 8740, 4859],
 [7481, 2191, 235, 2600]]

In [28]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [29]:
import numpy as np

In [30]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9128 5596 8740 2201]
 [   0    0    0    0 9128 5596 8740 5864]
 [   0    0    0    0 9128 8216 8740 7432]
 [   0    0    0 4452 7897  594 2600 4104]
 [   0    0    0 4452 7897  594 2600   50]
 [   0    0    0 3889 9128 1393 8740 4859]
 [   0    0    0    0 7481 2191  235 2600]]


In [16]:
## feature representation
dim=10

In [34]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [35]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step


array([[[-0.00025491,  0.0487479 ,  0.01644908,  0.03508072,
          0.01441517,  0.04804171,  0.03833229,  0.03563334,
         -0.00880044, -0.04305236],
        [-0.00025491,  0.0487479 ,  0.01644908,  0.03508072,
          0.01441517,  0.04804171,  0.03833229,  0.03563334,
         -0.00880044, -0.04305236],
        [-0.00025491,  0.0487479 ,  0.01644908,  0.03508072,
          0.01441517,  0.04804171,  0.03833229,  0.03563334,
         -0.00880044, -0.04305236],
        [-0.00025491,  0.0487479 ,  0.01644908,  0.03508072,
          0.01441517,  0.04804171,  0.03833229,  0.03563334,
         -0.00880044, -0.04305236],
        [-0.04895509,  0.00659329,  0.0291375 ,  0.02773739,
          0.02989371,  0.02979902,  0.01475134,  0.00293343,
         -0.02097276, -0.01942652],
        [ 0.00220565, -0.0120121 , -0.0269111 , -0.0148576 ,
          0.00697242, -0.043495  ,  0.01094921,  0.00051124,
         -0.04915416,  0.01000559],
        [-0.01345984,  0.01444203,  0.04158575,  0.0

In [37]:
embedded_docs[0]

array([   0,    0,    0,    0, 9128, 5596, 8740, 2201], dtype=int32)

In [39]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


array([[[-0.00025491,  0.0487479 ,  0.01644908,  0.03508072,
          0.01441517,  0.04804171,  0.03833229,  0.03563334,
         -0.00880044, -0.04305236],
        [-0.00025491,  0.0487479 ,  0.01644908,  0.03508072,
          0.01441517,  0.04804171,  0.03833229,  0.03563334,
         -0.00880044, -0.04305236],
        [-0.00025491,  0.0487479 ,  0.01644908,  0.03508072,
          0.01441517,  0.04804171,  0.03833229,  0.03563334,
         -0.00880044, -0.04305236],
        [-0.00025491,  0.0487479 ,  0.01644908,  0.03508072,
          0.01441517,  0.04804171,  0.03833229,  0.03563334,
         -0.00880044, -0.04305236],
        [-0.04895509,  0.00659329,  0.0291375 ,  0.02773739,
          0.02989371,  0.02979902,  0.01475134,  0.00293343,
         -0.02097276, -0.01942652],
        [ 0.00220565, -0.0120121 , -0.0269111 , -0.0148576 ,
          0.00697242, -0.043495  ,  0.01094921,  0.00051124,
         -0.04915416,  0.01000559],
        [-0.01345984,  0.01444203,  0.04158575,  0.0